### ISSUE TITLE
Generated select item links added to report seem to not reflect current link format

### ISSUE THREAD

**Issue by acsr** [retorquere/zotero-report-customizer#42]
There was an ancient issue on select items links that missed an actual full example link. https://github.com/retorquere/zotero-report-customizer/issues/4#issue-28578838.

## Links not working

For me the issue seems to remain. 
I use latest Zotero Report Customizer 5.0.32 in Zotero 5.0.80 on MacOS 10.13.6

* Clicking a select link in the report does not work
* Manual copy of the link to a browser and open it does not work

no obvious 404 error shows up in Zotero.

### Select links in general are working

I have Zutilo installed and it delivers working select item links that are redirected well by e.g. Chrome to Zotero and opens them in main library and groups as well.

examples of working links extracted by Zutilo:

`zotero://select/library/items/R6UEJGB8`
`zotero://select/groups/1234567/items/R6UEJGB8`

instead the Zotero Report Customizer generates links in the form:

`zotero://select/items/0_R6UEJGB8` where `R6UEJGB8` matches the id of the items above. The form does not differ for groups or the library and prefixes the id with `zero-underscore` `0_`

The examples are anonymised and work as reference. The actual id would not be the same for existing group or library items.

Please take a look at the code for retrieving these links and / or give me a hint if I am wrong.

### Zotero URI 

Instead of the select items links that work only on local installs an option to include the **Zotero URI** instead or additionally would be fine, since reports usually are used to share information with others. This makes in practise more sense for items with shared access in groups. But if you are in the public they can be useful für users as well to access the item via web after login.

`https://www.zotero.org/users/12345/items/R6UEJGB8`
`https://www.zotero.org/groups/1234567/items/R6UEJGB8`

### Options to in/exclude more items

* Globally exclude the Zotero links (Select Item Link and/or Zotero URI)
* Exclude a whole particular note subitem with an interface similar to the main metadata
* Add Zotero Links to related items and attachments (currently for me the attachment link in the report points to the source URI.)

Thanks for the wonderful Plugin anyway!

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.32.148](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.32.148.xpi) ("fixes #42")

Install in Zotero by downloading [test build 5.0.32.148](https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.32.148.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Yep, I generally prefer separate tickets. In this case:

* links should be fixed in build 148
* there's a hidden preference (see https://github.com/retorquere/zotero-report-customizer/blob/gh-42/README.md) which turns select-links into web-links

As to the rest, please in separate tickets, but I do have the following questions:

* What value would there be in removing the links?
* I don't think I'm going to do excluding of particular items. It'd be a lot of work, and if you don't want them in the report, don't select them ¯\\\_(ツ)\_/¯
* related links is doable I think.

**Comment by retorquere** [comment]
Does build 148 solve the problem for you?

**Comment by retorquere** [comment]
closing for inactivity.

**Comment by acsr** [comment]
Hi, unfortunately the notifies on this issue went completely by. I will report asap even if the ticket is closed. Missing feedback is a nogo. Sorry. But currently Report Customizer drops an issue in Zotero for me, this is why I visited your repo. I was surprised that I filed in a ticket and forgot it. Shame on me.

**Comment by acsr** [comment]
Hi, unfortunately the select items links for group libraries are still not working with Zotero Report Customizer (5.0.34, extension), I tried to get the test build https://github.com/retorquere/zotero-report-customizer/releases/download/builds/zotero-report-customizer-5.0.32.148.xpi but it seems to be gone.

Seems that this commit https://github.com/retorquere/zotero-report-customizer/commit/e2ce25393e6cca9d9306dfc6aa7bc28712b52dc1 is still in the current 5.0.34 latest.

For example:

I can fetch a working select link of an item in a group library using the Zutilo PlugIn:

zotero://select/groups/7975/items/LWBDPMJ4

Report customizer still prints:

zotero://select/library/items/LWBDPMJ4

You cannot test this using these links, because all my group libraries are private.

Please use a group library you own.

I guess the expression in the if statement fails. I currently have no clue to create the code to lookup the proper values from Zotero to decide if its a group library or call a debugger to see whats going on.

Here is my setup:

version => 5.0.96.2, platform => MacIntel, oscpu => Intel Mac OS X 10.14, locale => de, appName => Zotero, appVersion => 5.0.96.2, extensions => Zotero Storage Scanner (5.0.8, extension), ZoteroQuickLook (1.4.2, extension), Zotero Report Customizer (5.0.34, extension), ZotFile (5.0.16, extension), Zotero LibreOffice Integration (5.0.25.SA.5.0.96.2, extension), Zutilo Dienstprogramm für Zotero (3.9.0, extension), Better BibTex for Zotero (5.4.23, extension), Zotero Word for Mac Integration (5.0.36.SA.5.0.96.2, extension, disabled)

**Comment by acsr** [comment]
One more point: the first line of the if statement at https://github.com/retorquere/zotero-report-customizer/commit/e2ce25393e6cca9d9306dfc6aa7bc28712b52dc1#diff-9b29adc1ef673568f7176e662ef19f3caf35e8d5d1074291b754f0e795918939R36 sems to ignore the difference between group and main library links if the web flag is set.

The correct item web URI is https://www.zotero.org/groups/7975/items/LWBDPMJ4

Tipp: Zutilo differenciates between Zotero **select item links** and **Zotero URI**, this terminology helps not to confuse both. So you actually need two nested if statements.

One 

decision for the web flag

and a

seperate decision to figure out if it is a group library.
